{% set name = "ditaa" %}
{% set version = "0.11.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/stathissideris/ditaa/releases/download/v0.11.0/ditaa-0.11.0-standalone.jar
  sha256: 9418aa63ff6d89c5d2318396f59836e120e75bea7a5930c4d34aa10fe7a196a9

build:
  noarch: generic
  number: 0

requirements:
  build:
  host:
  run:
    - openjdk
    - python

test:
  commands:
    - ditaa --help

about:
  home: https://github.com/stathissideris/ditaa
  license: LGPL-3.0-only
  license_family: LGPL
  license_file: LICENSE
  summary: 'DIagrams Through Ascii Art'
  # The remaining entries in this section are optional, but recommended.
  description: |
    ditaa is a small command-line utility that can convert 
    diagrams drawn using ascii art ('drawings' that contain 
    characters that resemble lines like | / - ), into 
    proper bitmap graphics. 
  doc_url: https://ditaa.sourceforge.net/
  dev_url: https://github.com/stathissideris/ditaa

extra:
  recipe-maintainers:
    - ajaypnair09
