{% set name = "ditaa" %}
{% set version = "0.11.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/stathissideris/{{ name }}/archive/refs/tags/v{{ version }}.tar.gz
  sha256: 0cd69b13febd285d90fcdc220e81158aae0cba54c6d6bdfd38d97e708c611ebd

build:
  number: 0

requirements:
  build:
    - openjdk
  run:
    - openjdk
    - python

test:
  commands:
    - ditaa --help

about:
  home: https://github.com/stathissideris/ditaa
  license: LGPL-3.0-only
  license_family: LGPL
  license_file: LICENSE
  summary: 'DIagrams Through Ascii Art'
  # The remaining entries in this section are optional, but recommended.
  description: |
    ditaa is a small command-line utility that can convert 
    diagrams drawn using ascii art ('drawings' that contain 
    characters that resemble lines like | / - ), into 
    proper bitmap graphics. 
  doc_url: https://ditaa.sourceforge.net/
  dev_url: https://github.com/stathissideris/ditaa

extra:
  recipe-maintainers:
    - ajaypnair09
